name: Test

on:
  push:
    branches:
      - dev
      - dev-next
      - next
      - beta
      - "*.x" # maintenance releases branches

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        # os: [ubuntu-latest, windows-latest, macOS-latest] Will re-enable at a later time

    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      - name: Run Tests
        run: deno test -A --unstable ./test/test.ts
