name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        # os: [ubuntu-latest, windows-latest, macOS-latest] Will re-enable at a later time

    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      - name: Run Tests
        run: deno test -A --unstable ./test/test.ts
