name: Test

on:
  push:
    branches:
      - dev
      - dev-next
      - next
      - beta
      - "*.x" # maintenance releases branches

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@2
        with:
          deno-version: ${{ matrix.deno }} # tests across multiple Deno versions

      - name: Download Test DB
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "https://github.com/maxmind/MaxMind-DB/raw/main/test-data/GeoLite2-City-Test.mmdb"
          target: test/

      - name: Run Tests
        run: deno test -A --unstable ./test/deno.ts
